name: Playwright Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  feature-tests:
    name: Feature Tests (Parallel)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run feature tests (parallel)
        run: |
          pytest -n auto -m "not serial"

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-feature-results
          path: allure-results

  e2e-tests:
    name: E2E Tests (Serial)
    runs-on: ubuntu-latest
    needs: feature-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run E2E tests (serial)
        run: |
          pytest -m serial

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-e2e-results
          path: allure-results
